# Generated by Django 5.0.14 on 2026-09-10 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('indigo_api', '0062_documenteditlease_activity_nonce'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Full display name, e.g. 'Accounting Section' or 'Sustainable Finance Group'", max_length=200, unique=True)),
                ('short_code', models.CharField(help_text="Short identifier for URLs / compact display, e.g. 'ACC' or 'SFG'", max_length=20, unique=True)),
                ('division', models.CharField(choices=[('PRD', 'Prudential Regulation Division'), ('COD', 'Conduct and Operations Division')], max_length=3)),
                ('group_name', models.CharField(help_text='Parent Group name. Equal to `name` when this unit IS the group (no sub-Sections).', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['division', 'group_name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MDOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_restricted', models.BooleanField(default=False, help_text='If False, any working unit can edit. If True, edits are blocked for units listed in denied_units.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='md_ownership', to='indigo_api.work')),
                ('denied_units', models.ManyToManyField(blank=True, help_text='Units explicitly denied edit rights. Only consulted if edit_restricted=True.', related_name='denied_from_mds', to='rbi_registry_app.workingunit')),
                ('nodal_unit', models.ForeignKey(help_text='The unit responsible for this MD; typically leads amendment reviews.', on_delete=django.db.models.deletion.PROTECT, related_name='nodal_for_mds', to='rbi_registry_app.workingunit')),
            ],
        ),
        migrations.CreateModel(
            name='UnitMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('joined_at', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_memberships', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='rbi_registry_app.workingunit')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'is_primary'], name='rbi_registr_user_id_c7291e_idx')],
                'unique_together': {('user', 'unit')},
            },
        ),
        migrations.CreateModel(
            name='DraftAmendment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_eid', models.CharField(help_text="AKN element ID being modified, e.g. 'chp_II__para_6__ii'. Not a DB FK — validated as-existing in current MD by application logic.", max_length=200)),
                ('change_type', models.CharField(choices=[('insert', 'Insert new provision'), ('modify', 'Modify existing text'), ('delete', 'Delete provision'), ('renumber', 'Renumber provisions')], max_length=20)),
                ('proposed_text', models.TextField(blank=True, help_text="The new content. Empty for change_type='delete'.")),
                ('rationale', models.TextField(blank=True, help_text='Optional explanation of why this change is proposed.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('author_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_amendments', to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_amendments', to='indigo_api.work')),
                ('author_unit', models.ForeignKey(help_text="Denormalized from author_user's primary UnitMembership at creation time. Preserves historical attribution when users move between units.", on_delete=django.db.models.deletion.PROTECT, related_name='amendments', to='rbi_registry_app.workingunit')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['work', 'target_eid', 'status'], name='rbi_registr_work_id_33635c_idx'), models.Index(fields=['author_unit', 'status'], name='rbi_registr_author__ae3994_idx')],
            },
        ),
    ]
